### ISSUE TITLE
wayvncctl: Segmentation fault in help command

### ISSUE THREAD

**Issue by any1** [any1/wayvnc#211]
```
./build/wayvncctl help --command=foobar
```

Backtrace:
```
#0  0x000055555555919e in print_command_usage (cmd_name=0x555555560910 "foobar",
    cmd_options=0x7ffffffed690, parent_options=0x7fffffff5b20)
    at ../src/ctl-client.c:653
#1  0x0000555555559427 in ctl_client_print_help (self=0x5555555602a0,
    request=0x5555555609d0, cmd_options=0x7ffffffed690,
    parent_options=0x7fffffff5b20) at ../src/ctl-client.c:702
#2  0x0000555555559840 in ctl_client_run_command (self=0x5555555602a0,
    parent_options=0x7fffffff5b20, flags=0) at ../src/ctl-client.c:785
#3  0x00005555555567d7 in main (argc=3, argv=0x7fffffffe078)
    at ../src/wayvncctl.c:123
```

**Comment by lack** [comment]
Hmmm, thought I caught all of these :(

On it!
