### ISSUE TITLE
Segmentation Fault: Could not bind to IP

### ISSUE THREAD

**Issue by FuckingToasters** [any1/wayvnc#281]
### Useful information:
Please, try to gather as much of useful information as possible and follow
these instructions:

- **Version:**
  wayvnc: v0.8-dev-f2c9ab0 (master)
  neatvnc: v0.8-dev-d80b51f (master)
  aml: v0.3.0-1-gede4249 (master)

- Try to reproduce while capturing a **trace log:**
  ```
  [infinimonster@XeroArch ~]$ wayvnc/./build/wayvnc 212.18.30.109 -Ltrace | tee wayvnc-crash.log
  TRACE: ../src/main.c: 257: Registering new wlr_output_power_manager
  TRACE: ../src/main.c: 265: Registering new wlr_output_manager
  TRACE: ../src/main.c: 247: Registering new xdg_output_manager
  TRACE: ../src/main.c: 228: Registering new output 49
  TRACE: ../src/output-management.c: 184: New head, now at 1
  TRACE: ../src/output-management.c: 42: Got head name: eDP-1
  TRACE: ../src/output-management.c: 51: Got head description: LG Display 0x04A5 (eDP-1)
  TRACE: ../src/output-management.c: 58: Got head size: 250x170
  TRACE: ../src/output-management.c: 65: Got head mode
  TRACE: ../src/output-management.c: 65: Got head mode
  TRACE: ../src/output-management.c: 71: Got head enabled: yes
  TRACE: ../src/output-management.c: 80: Got head current mode
  TRACE: ../src/output-management.c: 86: Got head position: 0,0
  TRACE: ../src/output-management.c: 92: Got head transform: 0
  TRACE: ../src/output-management.c: 99: Got head scale: 1.00
  TRACE: ../src/output-management.c: 162: Got new serial: 1
  TRACE: ../src/output.c: 226: Output 49 name: eDP-1, headless: no
  TRACE: ../src/output.c: 236: Output 49 description: LG Display 0x04A5 (eDP-1)
  TRACE: ../src/output.c: 279: Output eDP-1 power state changed to ON
  Info: Capturing output eDP-1
  Info: >> LG Display 0x04A5 (eDP-1) 1920x1280+0x0 Power:ON
  DEBUG: ../subprojects/neatvnc/src/server.c: 1810: Trying address: 212.18.30.109
  DEBUG: ../subprojects/neatvnc/src/server.c: 1834: Failed to bind to address: Cannot assign requested address
  ERROR: ../src/main.c: 877: Failed to bind to address. Add -Ldebug to the argument list for more info.
  ```

- Get the **stack trace**:
    ```
    [infinimonster@XeroArch ~]$ coredumpctl gdb wayvnc
           PID: 3562 (wayvnc)
           UID: 1000 (infinimonster)
           GID: 1000 (infinimonster)
           Signal: 11 (SEGV)
           Timestamp: Thu 2023-11-30 10:18:13 CET (1min 49s ago)
        Command Line: wayvnc/./build/wayvnc 212.18.30.109 -Ltrace
          Executable: /home/infinimonster/wayvnc/build/wayvnc
       Control Group: /user.slice/user-1000.slice/session-2.scope
                Unit: session-2.scope
               Slice: user-1000.slice
             Session: 2
           Owner UID: 1000 (infinimonster)
             Boot ID: 012c361b871e499b961b3419a6f9e5a2
          Machine ID: e9f1204ccca34d4591d994bc501a1303
            Hostname: XeroArch
             Storage: /var/lib/systemd/coredump /core.wayvnc.1000.012c361b871e499b961b3419a6f9e5a2.3562.1701335893000000.zst (present)
        Size on Disk: 1013.5K
             Message: Process 3562 (wayvnc) of user 1000 dumped core.
                      
                      Stack trace of thread 3562:
                      #0  0x00007fb19e9b8e70 n/a (/home/infinimonster/wayvnc/build/subprojects/aml/libaml.so.0.0.0 + 0x3e70)
                      #1  0x00007fb19e9b8858 n/a (/home/infinimonster/wayvnc/build/subprojects/aml/libaml.so.0.0.0 + 0x3858)
                      #2  0x000055b2b9d37d71 n/a (/home/infinimonster/wayvnc/build/wayvnc + 0xed71)
                      #3  0x000055b2b9d37df7 n/a (/home/infinimonster/wayvnc/build/wayvnc + 0xedf7)
                      #4  0x000055b2b9d32e51 n/a (/home/infinimonster/wayvnc/build/wayvnc + 0x9e51)
                      #5  0x000055b2b9d33081 n/a (/home/infinimonster/wayvnc/build/wayvnc + 0xa081)
                      #6  0x000055b2b9d379de n/a (/home/infinimonster/wayvnc/build/wayvnc + 0xe9de)
                      #7  0x00007fb19e55ccd0 n/a (libc.so.6 + 0x27cd0)
                      #8  0x00007fb19e55cd8a __libc_start_main (libc.so.6 + 0x27d8a)
                      #9  0x000055b2b9d31cb5 n/a (/home/infinimonster/wayvnc/build/wayvnc + 0x8cb5)
                      ELF object binary architecture: AMD x86-64
    ```

- Describe how to **reproduce** the problem:
- When starting it without specifying any ip ( so it uses 127.0.0.1) it works fine, it also works fine when specifying 0.0.0.0 but when trying to specify the public ip shown with the `curl ifconfig.me` command, then the errir above happens.

I already looked into the 2 simmilar issues and tried the fix with the display.c file in the neatvnc folder but it did not solve it for me.

![image](https://github.com/any1/wayvnc/assets/94435104/98276c83-58a9-44b7-bdbb-f5d37f2e592a)

**Comment by FuckingToasters** [comment]
> This is `EADDRNOTAVAIL` returned from the `bind` system call. Which, according to the man page, means:
> 
> > A nonexistent interface was requested or the requested address was not local.
> 
> None the less, it is a bug because it shouldn't segfault on exit.

Well the issue is that i can't connect from a different network even when using 0.0.0.0 so i tried to use the public ip instead which caused the error

**Comment by any1** [comment]
Seems like an issue with your network. I would try something else like starting a `netcat` server and trying to connect to it externally, checking if there are any firewall rules that might be getting in the way; things like that...

**Comment by FuckingToasters** [comment]
> Seems like an issue with your network. I would try something else like starting a `netcat` server and trying to connect to it externally, checking if there are any firewall rules that might be getting in the way; things like that...

That's why, yea I tried it in my school. At home everything worked as expected. Closing this as completed now.

**Comment by layercak3** [comment]
I'd reopen this, since the segfault still occurs in libaml after a bind/listen failure message using latest aml/wayvnc. To reproduce, just cause [this](https://github.com/any1/wayvnc/blob/b7de0d9fa6d7d44f78aad540fdae749e80773dea/src/main.c#L905) error to occur, such as when binding to a nonlocal address, or if using my patch, using an inappropriate fd that would cause listen() to fail. Here's a more complete backtrace:
```
(gdb) bt full
#0  0x00007ffff7fbae70 in aml_ref (obj=0x0) at ../../worktrees/master/subprojects/aml/src/aml.c:891
        self = 0x0
        __PRETTY_FUNCTION__ = "aml_ref"
        ref = 21845
#1  0x00007ffff7fba858 in aml_stop (self=0x5555555b9e40, obj=0x0) at ../../worktrees/master/subprojects/aml/src/aml.c:726
#2  0x000055555556313e in screencopy__stop (self=0x7fffffff5e88) at ../../worktrees/master/src/screencopy.c:42
#3  0x00005555555631c4 in screencopy_stop (self=0x7fffffff5e88) at ../../worktrees/master/src/screencopy.c:58
#4  0x000055555555df47 in wayland_detach (self=0x7fffffff5da0) at ../../worktrees/master/src/main.c:430
#5  0x000055555555e187 in wayvnc_destroy (self=0x7fffffff5da0) at ../../worktrees/master/src/main.c:484
#6  0x0000555555562dab in main (argc=2, argv=0x7fffffffe508) at ../../worktrees/master/src/main.c:2009
        self = {do_exit = false, display = 0x5555555ba160, registry = 0x5555555be310, wl_handler = 0x0, outputs = {prev = 0x7fffffff5dc0, next = 0x7fffffff5dc0}, seats = {prev = 0x7fffffff5dd0, next = 0x7fffffff5dd0}, cfg = {directory = 0x0, enable_auth = false, relax_encryption = false, private_key_file = 0x0, certificate_file = 0x0, rsa_private_key_file = 0x0, username = 0x0, password = 0x0, address = 0x0, port = 0, enable_pam = false, xkb_rules = 0x0, xkb_model = 0x0, xkb_layout = 0x0, xkb_variant = 0x0, xkb_options = 0x0, use_relative_paths = false}, keyboard_manager = 0x5555555c01f0, pointer_manager = 0x5555555c0380, data_control_manager = 0x5555555bf3c0, transient_seat_manager = 0x5555555c0260, selected_output = 0x0, selected_seat = 0x0, screencopy = {status = SCREENCOPY_STOPPED, pool = 0x0, front = 0x0, back = 0x0, manager = 0x5555555bf230, frame = 0x0, userdata = 0x7fffffff5da0, on_done = 0x555555560281 <on_capture_done>, last_time = 0, start_time = 0, timer = 0x0, delay_smoother = {time_constant = 0, last_time = 0, last_result = 0}, delay = 0, is_immediate_copy = false, overlay_cursor = false, wl_output = 0x0, wl_shm_width = 0, wl_shm_height = 0, wl_shm_stride = 0, wl_shm_format = WL_SHM_FORMAT_ARGB8888, have_linux_dmabuf = false, enable_linux_dmabuf = false, dmabuf_width = 0, dmabuf_height = 0, fourcc = 0, rate_limit = 30}, wayland_handler = 0x0, signal_handler = 0x0, nvnc = 0x0, nvnc_display = 0x0, kb_layout = 0x0, kb_variant = 0x0, damage_area_sum = 0, n_frames_captured = 0, disable_input = false, use_transient_seat = false, nr_clients = 0, performance_ticker = 0x0, capture_retry_timer = 0x0, ctl = 0x0, is_initializing = false, start_detached = false, master_layout_client = 0x0}
        cfg_file = 0x0
        enable_gpu_features = false
        address = 0x7fffffff5fc0 "0.0.0.1"
        port = 5900
        use_unix_socket = false
        use_websocket = false
        start_detached = false
        output_name = 0x0
        seat_name = 0x0
        socket_path = 0x0
        keyboard_options = 0x0
        overlay_cursor = false
        show_performance = false
        max_rate = 30
        disable_input = false
        use_transient_seat = false
        drm_fd = -1
        log_level = 2
        opts = {{short_opt = 0 '\000', long_opt = 0x0, schema = 0x0, help = 0x555555572060 "The IP address or unix socket path to listen on.", default_ = 0x555555571e6a "127.0.0.1", positional = 0x555555571d3e "address", is_subcommand = false}, {short_opt = 0 '\000', long_opt = 0x0, schema = 0x0, help = 0x555555572091 "The TCP port to listen on.", default_ = 0x5555555720ac "5900", positional = 0x555555571d46 "port", is_subcommand = false}, {short_opt = 67 'C', long_opt = 0x555555571cac "config", schema = 0x5555555720b1 "<path>", help = 0x5555555720b8 "Select a config file.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 103 'g', long_opt = 0x555555571cb3 "gpu", schema = 0x0, help = 0x5555555720d0 "Enable features that need GPU.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 111 'o', long_opt = 0x555555571cb7 "output", schema = 0x5555555720ef "<name>", help = 0x5555555720f6 "Select output to capture.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 107 'k', long_opt = 0x555555571d35 "keyboard", schema = 0x555555572110 "<layout>[-<variant>]", help = 0x555555572128 "Select keyboard layout with an optional variant.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 115 's', long_opt = 0x555555571ad4 "seat", schema = 0x5555555720ef "<name>", help = 0x555555572159 "Select seat by name.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 83 'S', long_opt = 0x555555571cbe "socket", schema = 0x5555555720b1 "<path>", help = 0x55555557216e "Control socket path.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 116 't', long_opt = 0x555555571d1d "transient-seat", schema = 0x0, help = 0x555555572183 "Use transient seat.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 114 'r', long_opt = 0x555555571cc5 "render-cursor", schema = 0x0, help = 0x555555572198 "Enable overlay cursor rendering.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 102 'f', long_opt = 0x555555571d15 "max-fps", schema = 0x5555555721b9 "<fps>", help = 0x5555555721bf "Set rate limit.", default_ = 0x5555555721cf "30", positional = 0x0, is_subcommand = false}, {short_opt = 112 'p', long_opt = 0x555555571cd3 "performance", schema = 0x0, help = 0x5555555721d2 "Show performance counters.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 117 'u', long_opt = 0x555555571cdf "unix-socket", schema = 0x0, help = 0x5555555721ed "Create unix domain socket.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 100 'd', long_opt = 0x555555571cf5 "disable-input", schema = 0x0, help = 0x555555572208 "Disable all remote input.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 68 'D', long_opt = 0x555555571d2c "detached", schema = 0x0, help = 0x555555572228 "Start detached from a compositor.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 86 'V', long_opt = 0x555555571c9f "version", schema = 0x0, help = 0x55555557224a "Show version info.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 118 'v', long_opt = 0x555555571d03 "verbose", schema = 0x0, help = 0x555555572260 "Be more verbose. Same as setting --log-level=info", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 119 'w', long_opt = 0x555555571ceb "websocket", schema = 0x0, help = 0x555555572292 "Create a websocket.", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 76 'L', long_opt = 0x555555571d0b "log-level", schema = 0x5555555722a6 "<level>", help = 0x5555555722b0 "Set log level. The levels are: error, warning, info, debug trace and quiet.", default_ = 0x555555571c64 "warning", positional = 0x0, is_subcommand = false}, {short_opt = 104 'h', long_opt = 0x555555571ca7 "help", schema = 0x0, help = 0x5555555722fc "Get help (this text).", default_ = 0x0, positional = 0x0, is_subcommand = false}, {short_opt = 0 '\000', long_opt = 0x0, schema = 0x0, help = 0x0, default_ = 0x0, positional = 0x0, is_subcommand = false}}
        option_parser = {name = 0x555555573ee0 "Options", options = 0x555555579360 <opts>, n_opts = 20, values = {{option = 0x555555579360 <opts>, value = "0.0.0.1", '\000' <repeats 248 times>}, {option = 0x0, value = '\000' <repeats 255 times>} <repeats 127 times>}, n_values = 1, position = 1, remaining_argc = 0, remaining_argv = 0x0}
        port_str = 0x0
        __PRETTY_FUNCTION__ = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}
        cfg_rc = -1
        aml = 0x5555555b9e40
        socket_type = SOCKET_TYPE_TCP
        ctl_actions = {userdata = 0x0, on_attach = 0x0, on_detach = 0x0, on_output_cycle = 0x0, on_output_switch = 0x0, on_disconnect_client = 0x0, on_wayvnc_exit = 0x0, client_next = 0x0, client_info = 0x0, get_output_list = 0x0}
```

**Comment by any1** [comment]
Last commit should fix the segfault.
