### ISSUE TITLE
Assertion failed when output resolution changes

### ISSUE THREAD

**Issue by Xyene** [any1/wayvnc#49]
I encountered this crash while changing the resolution of the headless output, and reloading sway:

```
wayvnc: ../src/main.c:538: wayvnc_process_frame: Assertion `height == nvnc_fb_get_height(self->buffer)' failed.
```

<details><summary>GDB trace</summary>

```
>>> bt full
#0  0x00007fb5da555761 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007fb5da53f55b in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007fb5da53f42f in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#3  0x00007fb5da54e092 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#4  0x000056225c4cdfc2 in wayvnc_process_frame (self=0x7ffc930c09b0) at ../src/main.c:538
        format = 875709016
        width = 3000
        height = 2001
        is_first_frame = false
        __PRETTY_FUNCTION__ = "wayvnc_process_frame"
        fb = 0xbfd221187e7c06e1
#5  0x000056225c4ce26d in on_capture_done (capture=0x7ffc930c0ba0) at ../src/main.c:604
        self = 0x7ffc930c09b0
#6  0x000056225c4d15b2 in screencopy_ready (data=0x7ffc930c0ba0, frame=0x56225d2371b0, sec_hi=0, sec_lo=1027256, nsec=492180596) at ../src/screencopy.c:169
        self = 0x7ffc930c0ba0
        delay = 0.13299800000000001
#7  0x00007fb5da417ccd in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
No symbol table info available.
#8  0x00007fb5da41725a in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
No symbol table info available.
#9  0x00007fb5da7281c0 in ?? () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#10 0x00007fb5da724ad8 in ?? () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#11 0x00007fb5da72608c in wl_display_dispatch_queue_pending () from /lib/x86_64-linux-gnu/libwayland-client.so.0
No symbol table info available.
#12 0x000056225c4cd7dd in on_wayland_event (obj=0x56225d179700) at ../src/main.c:346
        self = 0x7ffc930c09b0
        rc = 0
        __PRETTY_FUNCTION__ = "on_wayland_event"
#13 0x00007fb5da97a6fb in aml__handle_event (self=0x56225d179030, obj=0x56225d179700) at ../subprojects/aml/src/aml.c:711
No locals.
#14 0x00007fb5da97a883 in aml_dispatch (self=0x56225d179030) at ../subprojects/aml/src/aml.c:754
        sig_old = {
          __val = {2, 0, 0, 18446744073709551615, 140722775525728, 140419033179511, 94705590702496, 5856792624, 140722775525728, 140419033175204, 18446744070967910688, 94705590702128, 140722775525776, 140419033180041, 18446744069414584320, 94705590702128}
        }
        sig_new = {
          __val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}
        }
        obj = 0x56225d179700
#15 0x000056225c4ceb91 in main (argc=2, argv=0x7ffc930c0e78) at ../src/main.c:885
        self = {
          do_exit = false,
          display = 0x56225c95e120,
          registry = 0x56225c9622c0,
          outputs = {
            prev = 0x56225c963730,
            next = 0x56225c963730
          },
          seats = {
            prev = 0x56225c964128,
            next = 0x56225c964128
          },
          cfg = {
            enable_auth = false,
            private_key_file = 0x0,
            certificate_file = 0x0,
            username = 0x0,
            password = 0x0,
            address = 0x0,
            port = 0
          },
          xdg_output_manager = 0x56225c964790,
          keyboard_manager = 0x56225c963640,
          pointer_manager = 0x56225c963fa0,
          pointer_manager_version = 2,
          renderer = {
            display = 0x56225c999b30,
            context = 0x56225d07b810,
            output = 0x56225c963720,
            read_format = 6408,
            read_type = 5121,
            frame_fbo = {{
                rbo = 0,
                fbo = 1,
                tex = 1
              }, {
                rbo = 0,
                fbo = 2,
                tex = 2
              }},
            frame_index = 1,
            damage_fbo = {
              rbo = 1,
              fbo = 3,
              tex = 0
            },
            frame_shader = {
              program = 3,
              u_tex0 = 1,
              u_proj = 0
            },
            damage_shader = {
              program = 6,
              u_tex0 = 0,
              u_tex1 = 1
            }
          },
          selected_output = 0x56225c963720,
          selected_seat = 0x56225c964120,
          dmabuf_backend = {
            fc = {
              status = CAPTURE_STOPPED,
              overlay_cursor = false,
              wl_output = 0x56225c964250,
              userdata = 0x7ffc930c09b0,
              on_done = 0x56225c4ce1a7 <on_capture_done>,
              frame_info = {
                fourcc_format = 0,
                width = 0,
                height = 0,
                stride = 0
              },
              damage_hint = {
                x = 0,
                y = 0,
                width = 0,
                height = 0
              },
              backend = {
                render = 0x56225c4d0cf9 <dmabuf_capture_render>,
                start = 0x56225c4d0bac <dmabuf_capture_start>,
                stop = 0x56225c4d0854 <dmabuf_capture_stop>
              }
            },
            manager = 0x56225c963500,
            zwlr_frame = 0x0,
            frame = {
              width = 0,
              height = 0,
              format = 0,
              n_planes = 0,
              plane = {{
                  fd = 0,
                  offset = 0,
                  size = 0,
                  pitch = 0,
                  modifier = 0
                }, {
                  fd = 0,
                  offset = 0,
                  size = 0,
                  pitch = 0,
                  modifier = 0
                }, {
                  fd = 0,
                  offset = 0,
                  size = 0,
                  pitch = 0,
                  modifier = 0
                }, {
                  fd = 0,
                  offset = 0,
                  size = 0,
                  pitch = 0,
                  modifier = 0
                }}
            },
            render_finish_time = 0,
            start_time = 0,
            timer = 0x56225d17f340
          },
          screencopy_backend = {
            frame_capture = {
              status = CAPTURE_DONE,
              overlay_cursor = false,
              wl_output = 0x56225c964250,
              userdata = 0x7ffc930c09b0,
              on_done = 0x56225c4ce1a7 <on_capture_done>,
              frame_info = {
                fourcc_format = 875709016,
                width = 3000,
                height = 2000,
                stride = 12000
              },
              damage_hint = {
                x = 0,
                y = 0,
                width = 3000,
                height = 2001
              },
              backend = {
                render = 0x56225c4d183b <screencopy_render>,
                start = 0x56225c4d170d <screencopy_start>,
                stop = 0x56225c4d132d <screencopy_stop>
              }
            },
            wl_shm = 0x56225c964700,
            buffer = 0x56225d17f4b0,
            pixels = 0x7fb53e10b000,
            bufsize = 24000000,
            manager = 0x56225c9635a0,
            frame = 0x0,
            last_time = 1027256499113,
            start_time = 1027256366115,
            timer = 0x56225d17f2b0,
            delay_smoother = {
              time_constant = 0.5,
              last_time = 1027256499113,
              last_result = 0.24489128082506439
            },
            delay = 0.24489128082506439,
            is_immediate_copy = false
          },
          capture_backend = 0x7ffc930c0ba0,
          pointer_backend = {
            vnc = 0x0,
            pointer = 0x56225c977cb0,
            current_mask = (unknown: 0),
            current_x = 2101,
            current_y = 485,
            output = 0x56225c963720
          },
          keyboard_backend = {
            virtual_keyboard = 0x56225c964ad0,
            context = 0x56225c964d30,
            keymap = 0x56225c9659d0,
            state = 0x56225c97a780,
            lookup_table_size = 512,
            lookup_table_length = 357,
            lookup_table = 0x56225c992100,
            key_state = {
              cap = 256,
              len = 3,
              storage = 0x56225c9655c0
            }
          },
          wayland_handler = 0x0,
          signal_handler = 0x0,
          nvnc = 0x56225d17efa0,
          nvnc_display = 0x56225d17f280,
          buffer = 0x56225d17f6b0,
          current_damage = {
            extents = {
              x1 = 0,
              y1 = 0,
              x2 = 0,
              y2 = 0
            },
            data = 0x7fb5da7e8b10
          },
          kb_layout = 0x0
        }
        cfg_file = 0x0
        address = 0x7ffc930c25a9 "0.0.0.0"
        port = 5900
        output_name = 0x0
        fcbackend = FRAME_CAPTURE_BACKEND_NONE
        seat_name = 0x0
        overlay_cursor = false
        shortopts = 0x56225c4d58fa "C:c:o:k:s:rh"
        longopts = {{
            name = 0x56225c4d5907 "config",
            has_arg = 1,
            flag = 0x0,
            val = 67
          }, {
            name = 0x56225c4d590e "frame-capturing",
            has_arg = 1,
            flag = 0x0,
            val = 99
          }, {
            name = 0x56225c4d591e "output",
            has_arg = 1,
            flag = 0x0,
            val = 111
          }, {
            name = 0x56225c4d5925 "keyboard",
            has_arg = 1,
            flag = 0x0,
            val = 107
          }, {
            name = 0x56225c4d592e "seat",
            has_arg = 1,
            flag = 0x0,
            val = 115
          }, {
            name = 0x56225c4d5933 "render-cursor",
            has_arg = 0,
            flag = 0x0,
            val = 114
          }, {
            name = 0x56225c4d5941 "help",
            has_arg = 0,
            flag = 0x0,
            val = 104
          }, {
            name = 0x0,
            has_arg = 0,
            flag = 0x0,
            val = 0
          }}
        n_args = 1
        cfg_rc = -1
        out = 0x56225c963720
        seat = 0x56225c964120
        renderer_input_type = RENDERER_INPUT_FB
        aml = 0x56225d179030
```

</details>

Not a huge problem, of course, since changing the resolution isn't a frequent action.

**Edit:** oops, just read the code and saw that that code path is clearly marked as `TODO` :)

**Comment by any1** [comment]
The process should now exit instead of aborting.
